image: node:18-alpine

pipelines:
  pull-requests:
    '**':
      - step:
          name: Debug Environment Variables
          script:
            - echo "Available environment variables:"
            - printenv

      - step:
          name: Check PR Source for Main
          script:
            - echo "Checking PR source branch..."
            - |
              if [ -n "$BITBUCKET_PR_DESTINATION_BRANCH" ]; then
                echo "PR destination is set to $BITBUCKET_PR_DESTINATION_BRANCH"
                if [ "$BITBUCKET_PR_DESTINATION_BRANCH" = "main" ]; then
                  echo "PR targets 'main'. Verifying source branch..."
                  if [ "$BITBUCKET_BRANCH" != "develop" ]; then
                    echo "Error: PR to 'main' must come from 'develop'. Current source branch is $BITBUCKET_BRANCH."
                    exit 1
                  else
                    echo "PR source branch is 'develop'. Check passed."
                  fi
                else
                  echo "PR does not target 'main', skipping source branch check."
                fi
              else
                echo "Not in a PR context, skipping source branch check."
              fi

      - step:
          name: Install Node.js, Angular CLI, and Dependencies
          script:
            - apk add --no-cache git
            - npm install -g @angular/cli
            - npm ci --force --legacy-peer-deps

      - step:
          name: Check and Run Tests
          script:
            - echo "Checking for test files..."
            - |
              if find ./projects -name "*.spec.ts" | grep -q .; then
                echo "Running tests..."
                npx ng test --watch=false

                if [ $? -ne 0 ]; then
                  echo "Tests failed."
                  exit 1
                fi
              else
                echo "No test files found. Skipping tests..."
              fi

      - step:
          name: Clean Up Merged Feature Branches
          script:
            - echo "Fetching all branches..."
            - |
              git fetch --all
              if [ "$BITBUCKET_PR_DESTINATION_BRANCH" = "develop" ]; then
                echo "PR is targeting 'develop'. Proceeding with branch cleanup..."
                merged_branches=$(git branch -r --merged origin/develop | grep -v '\->' | grep -E 'origin/feature-.*')
                echo "$merged_branches" | while read -r branch; do
                if [[ "$branch" =~ ^origin/feature- ]]; then
                  echo "Deleting merged branch ${branch#origin/}"
                  git push origin --delete "${branch#origin/}"
                fi
                done
              fi

      - step:
          name: Sync GitHub Mirror
          clone:
            enabled: false
          script:
            - echo "Cloning Bitbucket repository..."
            - git clone --bare git@bitbucket.org:sea-code-labs/angular-template.git
            - cd angular-template.git
            - echo "Pushing to GitHub mirror..."
            - git push --mirror git@github.com:sea-code-labs/angular-template.git

  branches:
    main:
      - step:
          name: Main
          script:
            - echo "Main branch..."

    develop:
      - step:
          name: Develop
          script:
            - echo "Develop branch..."

    '**':
      - step:
          name: Debug Environment Variables
          script:
            - echo "Available environment variables:"
            - printenv

      - step:
          name: Validate Branch Name
          script:
            - echo "Validating branch name..."
            - |
              if [[ ! "$BITBUCKET_BRANCH" =~ ^feature- ]]; then
                echo "Branch name must start with 'feature-'.";
                exit 1;
              fi

      - step:
          name: Install Node.js, Angular CLI, and Dependencies
          script:
            - apk add --no-cache git
            - npm install -g @angular/cli
            - npm ci --force --legacy-peer-deps

      - step:
          name: Check and Run Tests
          script:
            - echo "Checking for test files..."
            - |
              if find ./projects -name "*.spec.ts" | grep -q .; then
                echo "Running tests..."
                npx ng test --watch=false

                if [ $? -ne 0 ]; then
                  echo "Tests failed."
                  exit 1
                fi
              else
                echo "No test files found. Skipping tests..."
              fi

      - step:
          name: Sync GitHub Mirror
          clone:
            enabled: false
          script:
            - echo "Cloning Bitbucket repository..."
            - git clone --bare git@bitbucket.org:sea-code-labs/angular-template.git
            - cd angular-template.git
            - echo "Pushing to GitHub mirror..."
            - git push --mirror git@github.com:sea-code-labs/angular-template.git
