image: alpine/git:latest

pipelines:
  default:
    - step:
          name: Validate Branch and Commits
          script:
            - echo "Validating branch name and commit count..."
            - current_branch=$(git rev-parse --abbrev-ref HEAD)
            - if [[ ! "$current_branch" =~ ^feature- ]]; then
              echo "Error: Branch name must start with 'feature-'.";
              exit 1;
              fi
              
    - step:
        name: Clean Up Branches
        script:
          - echo "Fetching all branches..."
          - git fetch --all
          - echo "Cleaning up merged branches..."
          - git branch -r --merged origin/develop | grep -v '\->' | grep -v 'develop$' | while read -r branch; do
            git push origin --delete "${branch#origin/}";
            done

    - step:
        name: Sync GitHub Mirror
        clone:
          enabled: false
        script:
          - echo "Cloning Bitbucket repository..."
          - git clone --bare git@bitbucket.org:sea-code-labs/angular-template.git
          - cd angular-template.git
          - echo "Pushing to GitHub mirror..."
          - git push --mirror git@github.com:sea-code-labs/angular-template.git
