image: node:18

pipelines:
  pull-requests:
    '**':
      - step:
          name: Debug Environment Variables
          script:
            - echo "Available environment variables:"
            - printenv

      - step:
          name: Check PR Source for Main
          script:
            - echo "Checking PR source branch..."
            - |
              if [ -n "$BITBUCKET_PR_DESTINATION_BRANCH" ]; then
                echo "PR destination is set to $BITBUCKET_PR_DESTINATION_BRANCH"
                if [ "$BITBUCKET_PR_DESTINATION_BRANCH" = "main" ]; then
                  echo "PR targets 'main'. Verifying source branch..."
                  if [ "$BITBUCKET_BRANCH" != "develop" ]; then
                    echo "Error: PR to 'main' must come from 'develop'. Current source branch is $BITBUCKET_BRANCH."
                    exit 1
                  else
                    echo "PR source branch is 'develop'. Check passed."
                  fi
                else
                  echo "PR does not target 'main', skipping source branch check."
                fi
              else
                echo "Not in a PR context, skipping source branch check."
              fi

      - step:
          name: Run Tests
          script:
            - if [ ! -f "angular.json" ] || ! grep -q '"projects" { ' angular.json; then
              echo "No projects found in angular.json. Skipping tests.";
              exit 0;
              fi
            - echo "Installing dependencies..."
            - npm install
            - echo "Installing Google Chrome..."
            - apt-get update && apt-get install -y wget gnupg
            - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
            - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
            - apt-get update && apt-get install -y google-chrome-stable
            - echo "Setting CHROME_BIN environment variable..."
            - export CHROME_BIN=/usr/bin/google-chrome
            - echo "Running Karma tests..."
            - npm run test -- --browsers=ChromeHeadlessNoSandbox

      - step:
          name: Clean Up Merged Feature Branches
          script:
            - echo "Fetching all branches..."
            - |
              git fetch --all
              if [ "$BITBUCKET_PR_DESTINATION_BRANCH" = "develop" ]; then
                echo "PR is targeting 'develop'. Proceeding with branch cleanup..."
                merged_branches=$(git branch -r --merged origin/develop | grep -v '\->' | grep -E 'origin/feature-.*')
                echo "$merged_branches" | while read -r branch; do
                if [[ "$branch" =~ ^origin/feature- ]]; then
                  echo "Deleting merged branch ${branch#origin/}"
                  git push origin --delete "${branch#origin/}"
                  git fetch -p
                fi
                done
              else
                echo "PR is not targeting 'develop'."
              fi

      - step:
          name: Sync GitHub Mirror
          clone:
            enabled: false
          script:
            - echo "Cloning Bitbucket repository..."
            - git clone --bare git@bitbucket.org:sea-code-labs/angular-template.git
            - cd angular-template.git
            - echo "Pushing to GitHub mirror..."
            - git push --mirror git@github.com:sea-code-labs/angular-template.git

  branches:
    main:
      - step:
          name: Main
          script:
            - echo "Main branch..."

    develop:
      - step:
          name: Develop
          script:
            - echo "Develop branch..."

    '**':
      - step:
          name: Debug Environment Variables
          script:
            - echo "Available environment variables:"
            - printenv

      - step:
          name: Validate Branch Name
          script:
            - echo "Validating branch name..."
            - |
              if [[ ! "$BITBUCKET_BRANCH" =~ ^feature- ]]; then
                echo "Branch name must start with 'feature-'.";
                exit 1;
              fi

      - step:
          name: Run Tests
          script:
            - if [ ! -f "angular.json" ] || ! grep -q '"projects" { ' angular.json; then
              echo "No projects found in angular.json. Skipping tests.";
              exit 0;
              fi
            - echo "Installing dependencies..."
            - npm install
            - echo "Installing Google Chrome..."
            - apt-get update && apt-get install -y wget gnupg
            - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
            - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
            - apt-get update && apt-get install -y google-chrome-stable
            - echo "Setting CHROME_BIN environment variable..."
            - export CHROME_BIN=/usr/bin/google-chrome
            - echo "Running Karma tests..."
            - npm run test -- --browsers=ChromeHeadlessNoSandbox

      - step:
          name: Sync GitHub Mirror
          clone:
            enabled: false
          script:
            - echo "Cloning Bitbucket repository..."
            - git clone --bare git@bitbucket.org:sea-code-labs/angular-template.git
            - cd angular-template.git
            - echo "Pushing to GitHub mirror..."
            - git push --mirror git@github.com:sea-code-labs/angular-template.git
