pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - echo "Cloning Bitbucket repository..."
          - git clone --bare git@bitbucket.org:sea-code-labs/angular-template.git
          - cd angular-template.git
          - echo "Pushing to GitHub mirror..."
          - git push --mirror git@github.com:sea-code-labs/angular-template.git
