pipelines:
  default:
    - step:
        name: Clean up branches
        image: alpine/git:latest
        script:
          - echo "Fetching all branches..."
          - git fetch --all
          - echo "Cleaning up merged branches..."
          - git branch -r --merged origin/develop | grep -v '\->' | grep -v 'develop$' | while read -r branch; do
            git push origin --delete "${branch#origin/}";
            done
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - echo "Cloning Bitbucket repository..."
          - git clone --bare git@bitbucket.org:sea-code-labs/angular-template.git
          - cd angular-template.git
          - echo "Pushing to GitHub mirror..."
          - git push --mirror git@github.com:sea-code-labs/angular-template.git
