services:
  angular-app:
    # Build configuration
    build:
      # Path to the directory containing the Dockerfile
      context: .
      # The Dockerfile to use for building the image
      dockerfile: Dockerfile
      args:
        # Pass the APP environment variable to Docker build
        APP: ${APP}
    # Port mapping: Expose port 80 in the container on port 4200 of the host
    ports:
      - '4200:80'
    # Environment variables for the container
    environment:
      # Pass the APP environment variable to the container
      - APP=${APP}
    # Deployment settings
    deploy:
      resources:
        limits:
          # Maximum number of CPUs the container can use
          cpus: '2.0'
          # Maximum amount of memory the container can use
          memory: '2G'
    # Assign a specific name to the container for easier management
    container_name: angular-app-container
    # Automatically restart the container unless it is explicitly stopped
    restart: unless-stopped
